sudo: required
services:
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t eddym/react-test ./client

script:
  - docker run -e CI=true eddym/react-test npm test -- --coverage


after_success:
  - docker build -t eddym/multi-client ./client
  - docker build -t eddym/multi-nginx ./nginx
  - docker build -t eddym/multi-server ./server
  - docker build -t eddym/multi-worker ./worker

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master